### ISSUE TITLE
The error in data.py

### ISSUE THREAD

**Issue by Reze-Joe** [akhanss/BraTS-2020#1]
Thank you for sharing! But I find that always has ERROR like
File "/home/server/zMap/BraTS-2020-master-1/src/unet3d/data.py", line 53, in write_data_to_file
    n_channels = len(training_data_files[0]) - 1
IndexError: list index out of range

**Comment by akhanss** [comment]
@GearLeeess-JOE Could you please double-check whether your data path is properly configured in src/config_train.py or src/config_test.py?
You may debug adding the following line just after
```
n_channels = len(training_data_files[0]) - 1
print(n_channels)
```
It should not be printed 0!
