### ISSUE TITLE
ET, WT, TC and NCR/NET, ED, ET relations

### ISSUE THREAD

**Issue by ghost** [akhanss/BraTS-2020#2]
I am a little confused about the predicted labels. 

As described in the [data description](https://www.med.upenn.edu/cbica/brats2020/data.html), the segmentations label annotations are **the GD-enhancing tumor (ET — label 4), the peritumoral edema (ED — label 2), and the necrotic and non-enhancing tumor core (NCR/NET — label 1)**. However, the results you showed are in ET, WT, TC.

Using the training data, we can only infer the label annotations, which are NCR/NET, ED, ET. There should be some conversion between these annotations and ET, WT, TC, but I didn't see any implementation on this.

Could you please explain this confusion?

**Comment by akhanss** [comment]
@shizhigu97 Thanks a lot for the heads-up. Actually, we are directly dealing with the voxel 'numerical' label (1, 2 and 4), not 'textual' label NCR/NET, ED, ET and so on (please check the src/config.py file). The result I included in this repo is directly copied from the feedback of the CBICA judging system. I think they are using the previous year setup (perhaps forgot to modify header row ;))!

Nonetheless, I may need to post-process the output/prediction a bit to be aligned with this year's annotations for better results.

**Comment by ghost** [comment]
Yea, I see. What I am confused about is what format you upload to their judging system? Is it a segmentation map that consists of numerical values (0, )1,2, and 4?

**Comment by akhanss** [comment]
@shizhigu97 Yes, you are right.
