### ISSUE TITLE
memory dump while starting training

### ISSUE THREAD

**Issue by 1alebra2** [akhanss/BraTS-2020#5]
hello
I was trying to run your code (training) - thanks for sharing-, exactly as described and when  train_model starts I get a memory dump. I played with different image sizes and with patches, no change.  I am running on ubuntu 1.8, tf 1.15 with a RTX2080ti. This setting works with other nets.  Any help appreciated

**Comment by akhanss** [comment]
It is long time but others may face the same issue. I noticed the issue when I was trying to run the code recently. Here is the solution:
install pytables through conda
$ conda install pytables # please don't install though pip (pip install tables). It raises memory dump issue!
