### ISSUE TITLE
Issue in metrics.py while running on Colab

### ISSUE THREAD

**Issue by Prabhav55221** [akhanss/BraTS-2020#6]
Hi!
I am running this project on Google Colab using GPU. Everything works perfectly until it reaches the metrics.py file. Here it gives the following error:

![image](https://user-images.githubusercontent.com/43010772/106566431-5013cd80-6556-11eb-9f15-1f49ef75a976.png)

I assume this is due to an upgrade in the Tensorflow Library. Any suggestions on how to fix it?

**Comment by akhanss** [comment]
Sorry it is late I am replying to you. I tested the code on TensorFlow 1.15 (Python 3.7). I think, as you mentioned, the issue may raise due to updated TensorFlow library (2.x).
